### ISSUE TITLE
Output directory

### ISSUE THREAD

**Issue by eegeeZA** [horrible-little-slime/distro#1]
https://github.com/horrible-little-slime/distro/blob/de616e9427b19a1781794877abdea4b122c7f507/build.mjs#L18

If this is changed to something like `outdir: "dist/scripts/distro/scripts/horrible-little-slime"` it will be accessible to mafia for the `set chatbotScript=tubeChatbot.js` command. For now, I've copied it to my scripts folder manually.

**Comment by spaghetti-squash** [comment]
Thanks king

**Comment by eegeeZA** [comment]
Shot, works now 😉
